#!/usr/bin/env bash

echo docker run -it --rm --name mysqlterm --network my_network mysql:8.3 sh -c 'exec mysql -hmysql -P3306 -uroot -pdebezium'
docker run -it --rm --name mysqlterm --network my_network mysql:8.3 sh -c 'exec mysql -hmysql -P3306 -uroot -pdebezium'

