#!/usr/bin/env bash

#docker run -it --rm --name watcher-orders --network my_network -e ZOOKEEPER_CONNECT=zookeeper -e KAFKA_BROKER=kafka:9092 debezium/kafka:1.0 watch-topic -a -k orders
docker run -it --rm --name watcher-orders --network my_network -e ZOOKEEPER_CONNECT=zookeeper -e KAFKA_BROKER=kafka:9092 quay.io/debezium/kafka:2.4 watch-topic -a -k orders

