#!/usr/bin/env bash

#docker run -it --rm --name watcher --network my_network -e ZOOKEEPER_CONNECT=zookeeper -e KAFKA_BROKER=kafka:9092 debezium/kafka:1.0 watch-topic -a -k dbserver1.inventory.orders
docker run -it --rm --name watcher-dbserver1-orders --network my_network -e ZOOKEEPER_CONNECT=zookeeper -e KAFKA_BROKER=kafka:9092 quay.io/debezium/kafka:2.4 watch-topic -a -k dbserver1.inventory.orders

